### ISSUE TITLE
Unable to download new 3.6.0 version (stable)

### ISSUE THREAD

**Issue by pfiaux** [mongodb-js/runner#128]
When I try to run mongodb-runner with no options it tries to download mongo db 3.6.0 but I get the following error:

    Downloading mongodb-osx-x86_64-3.6.0.tgz
    Error: GET http://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.6.0.tgz returned 403

When checking for the urls here https://www.mongodb.org/dl/osx it looks like the 3.6.0 file is `osx/mongodb-osx-ssl-x86_64-3.6.0.tgz` so the `-ssl` is missing from the path (or the file without -ssl) is missing.

For now I could solve it using `MONGODB_VERSION=3.4.1`

This could be an issue with mongodb-version-manager but maybe limiting to the last functioning version here might help until the issue is resolve upstream.

**Comment by arubinofaux** [comment]
yup having same issue thanks for the `MONGODB_VERSION=3.4.1` tip

**Comment by durran** [comment]
Working on a fix - the download urls changed and need to update.

**Comment by durran** [comment]
This is fixed now - the certificates had expired and are now working again. No need to update any code.
