### ISSUE TITLE
where is my `mongod` binary file ?

### ISSUE THREAD

**Issue by zjh1943** [mongodb-js/runner#129]
My OS is macOS serria 10.13.3.

I run `npm install -g mongodb-runner` and `mongodb-runner start`. Then I can connect to mongodb now.
I know`mongodb-runner` is a starter of mongodb, but where is the origin `mongod` binary file ?

When I run `ps -ax | grep mongo`, it shows
```
 8455 ttys002    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn mongo
75158 ttys002    0:00.92 /usr/local/bin/node /usr/local/lib/node_modules/mongodb-runner/bin/mongodb-runner-worker.js --name=standalone --dbpath=/Users/zjh/.mongodb/data/standalone --logpath=/Users/zjh/.mongodb/runner/standalone.log --port=27017 --topology=standalone --mongodBin=mongod --mongosBin=mongos --purge=true --auth_mechanism=none
75161 ttys002    4:07.65 mongod --smallfiles --noprealloc --setParameter enableTestCommands=1 --port 27017 --dbpath /Users/zjh/.mongodb/data/standalone --logpath /Users/zjh/.mongodb/runner/standalone.log --nojournal
```
I saw the `mongod` command above. 
But when I run `mongod` in my shell, it said `command not found: mongod`.

So, does `mongodb-runner` install `mongo` for me? Where is the `mongod` file ?

For all I know, it is not in `/user/bin`, `/user/local/bin` or `/user/local/Cellar/`

**Comment by durran** [comment]
Should be installed in ` ~/.mongodb/versions/mongodb-current/bin`
