### ISSUE TITLE
run multiple versions at same time

### ISSUE THREAD

**Issue by freewil** [mongodb-js/runner#133]
It appears if you try to start multiple versions with different `MONGODB_VERSION` vars, it will kill the first instance.

Reproduce:
```
$ MONGODB_VERSION=2.4 MONGODB_PORT=27018 mongodb-runner start
$ MONGODB_VERSION=3.2 MONGODB_PORT=27017 mongodb-runner start
```

It'd be nice to be able to run multiple versions at the same time for development environments that require multiple versions of mongo.

**Comment by imlucas** [comment]
Yes, use `--name=version1` and `--name=version2`.

(Also don't use 2.4.x :p If you need to, I'd love to hear more)
