### ISSUE TITLE
Start failing because of space in User folder name on Windows

### ISSUE THREAD

**Issue by BernardZhao** [mongodb-js/runner#147]
So while trying to set up Parse, I ran these commands:
```
$ npm install -g mongodb-runner
$ mongodb-runner start
```

And got this error:

```mongodb-runner:bin:mongodb-runner-worker.js Unexpected error. Exiting. { Error: Command failed: mongod --setParameter enableTestCommands=1 --port 27017 --dbpath C:\mongodb\data\standalone --logpath C:\Users\Bernard Zhao/.mongodb/runner/standalone.log```

I did not find this error anywhere else after some Googling, and then tried running the command that failed by itself, and got this.

```
$ mongod --setParameter enableTestCommands=1 --port 27017 --dbpath C:\mongodb\data\standalone --logpath C:\Users\Bernard Zhao/.mongodb/runner/standalone.log
Invalid command: Zhao/.mongodb/runner/standalone.log
```

Which leads me to believe that the space in the name of my user folder on Windows caused start to fail. Is there any way that I can get around this? I would change the name of my user folder if I could, but there does not seem to be an easy way outside of reinstalling Windows 10. Any help would be appreciated!

**Comment by BernardZhao** [comment]
I found a way around this simply by providing a different argument to --logpath.

**Comment by renielDev** [comment]
Hi. I think im having the same issue. 

How did you resolved it? @BernardZhao

**Comment by haftado3** [comment]
just write some logpath outside of its normal path i used this command : `mongodb-runner start --logpath D:\mongolog.log`
