### ISSUE TITLE
Unknown command line arg --rest ??

### ISSUE THREAD

**Issue by mikecann** [mongodb-js/runner#148]
Hey, 

Love the project have been using it for years. For some reason lately I have started getting the following error when starting:

```
Starting a MongoDB deployment to test against...mongodb-runner:bin:mongodb-runner-worker.js Unexpected error. Exiting. { Error: Command failed: mongod --smallfiles --noprealloc --setParameter enableTestCommands=1 --port 27017 --dbpath C:\mongodb\data\standalone --logpath C:\Users\mikec/.mongodb/runner/standalone.log --rest --nojournal
Error parsing command line: unrecognised option '--rest'
try 'mongod --help' for more information

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'mongod --smallfiles --noprealloc --setParameter enableTestCommands=1 --port 27017 --dbpath C:\\mongodb\\data\\standalone --logpath C:\\Users\\mikec/.mongodb/runner/standalone.log --rest --nojournal' }
```

I think I [read something](https://stackoverflow.com/questions/47983629/error-parsing-command-line-unrecognized-option-rest?rq=1) that the `--rest` argument was removed from the latest mongodb, perhaps why its started happening?

**Comment by imlucas** [comment]
Thanks! You're correct. `--rest` and several other CLI flags were deprecated.

🤔 I updated to remove all of those last fall. What version of `mongodb-runner` are you on? We're now using latest, `mongodb-runner@4.7.1`, everywhere.

**Comment by mikecann** [comment]
@imlucas ye thats the version of mongodb-runner im on too. I had to set an environment var to `MONGODB_VERSION=3.2.22` to prevent the crashing 😄

**Comment by imlucas** [comment]
Interesting...

What OS and version are you running this on?

**Comment by mikecann** [comment]
Windows 10

**Comment by imlucas** [comment]
@mikecann Thanks. Looks like some other probs to bring in the new year... so I'll try to look at all of this over the weekend.
