### ISSUE TITLE
Unable to start runner on macOS Mojave

### ISSUE THREAD

**Issue by loic425** [mongodb-js/runner#150]
Version: 4.7.1

mongodb-runner start
The command is blocked on "Starting a MongoDB deployment to test against..."

**Comment by imlucas** [comment]
Hmmm I run this every day on mojave... Can you try the below and see if the debug output contains any more hints?

```
DEBUG=* mongodb-runner start
```

**Comment by loic425** [comment]
Thanks for the debug mode command. It don't know why but It works now.
