### ISSUE TITLE
No compatible version found: mongodb-tools@'mongodb-js/mongodb-tools'

### ISSUE THREAD

**Issue by ktt9117** [mongodb-js/runner#56]
I try to install. but I've got this message. 
How can I fix this? Please help me!

[root@web-3 node]# npm install -g mongodb-runner
npm http GET https://registry.npmjs.org/mongodb-runner
npm http 304 https://registry.npmjs.org/mongodb-runner
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/clui
npm http GET https://registry.npmjs.org/is-mongodb-running/0.0.1
npm http GET https://registry.npmjs.org/lodash.defaults
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mongodb
npm http GET https://registry.npmjs.org/mongodb-dbpath
npm http GET https://registry.npmjs.org/mongodb-version-manager
npm http GET https://registry.npmjs.org/untildify
npm http 304 https://registry.npmjs.org/clui
npm http 304 https://registry.npmjs.org/is-mongodb-running/0.0.1
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/mongodb
npm http 304 https://registry.npmjs.org/mongodb-dbpath
npm http 304 https://registry.npmjs.org/mongodb-version-manager
npm http 304 https://registry.npmjs.org/untildify
npm http 304 https://registry.npmjs.org/lodash.defaults
npm http GET https://registry.npmjs.org/mongodb-tools
npm http 304 https://registry.npmjs.org/mongodb-tools
npm ERR! Error: No compatible version found: mongodb-tools@'mongodb-js/mongodb-tools'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6"]
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-327.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "mongodb-runner"
npm ERR! cwd /home/node
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/node/npm-debug.log
npm ERR! not ok code 0
[root@web-3 node]#

**Comment by imlucas** [comment]
Hi @ktt9117!  

It appears your node.js version is quite old (0.10.42) and we can't support.  Is it possible for you to update the node.js version you're using on this machine?  Instructions can be found at https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager#setup-with-ubuntu

**Comment by ktt9117** [comment]
@imlucas Thanks. I'll try on it
