### ISSUE TITLE
Randomly stall after run

### ISSUE THREAD

**Issue by fleg** [mongodb-js/runner#60]
It just randomly stall with different versions of node and mongodb
examples:
[output](https://api.travis-ci.org/jobs/118552878/log.txt?deansi=true)
[travis-ci job](https://travis-ci.org/fleg/mongodbext/jobs/118552878)

**Comment by imlucas** [comment]
@fleg apologies.  this is issue we've been tracking for a long while now (see #51).  i'll dig back into it and see if i can get to the bottom of it.

**Comment by imlucas** [comment]
Reopened #51 and we'll merge this issue into it.
