### ISSUE TITLE
MongoDB Runner 3.3.0 does not have latest changes

### ISSUE THREAD

**Issue by TylerBrock** [mongodb-js/runner#75]
I think i might be going crazy but when I npm install mongodb-runner@3.3.0 it doesn't have the change you merged yesterday.

**Comment by TylerBrock** [comment]
I asked a colleague to check, npm installs 3.3.0 and it also doesn't have the storage engine options. Something is messed up with the published package.

**Comment by imlucas** [comment]
hmm.  just published 3.3.1. installed locally and confirmed #74 is in there.
<img width="461" alt="screen shot 2016-05-19 at 3 45 32 pm" src="https://cloud.githubusercontent.com/assets/23074/15407429/c4d95e8e-1dd8-11e6-9146-c1f7135bb3d5.png">

**Comment by TylerBrock** [comment]
works now, thx
