### ISSUE TITLE
3.2.2 fails due to graceful-fs module needing an update

### ISSUE THREAD

**Issue by adrianbrink** [mongodb-js/runner#78]
Hi,

I get this: 

> → mongodb-runner start
> (node:78820) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
>   ◟ Starting a MongoDB deployment to test against...(node:78821) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
>   ◟ Starting a MongoDB deployment to test against...%

**Comment by hoavo** [comment]
me too

**Comment by semiautomatix** [comment]
Same on 3.3.2 on Windows 10 preventing me from using parse-server

**Comment by cognitom** [comment]
I'm investing this issue.
The version of [downcache](https://github.com/wilson428/downcache) seems [old in mongodb-version-list](https://github.com/mongodb-js/mongodb-version-list/blob/v0.0.3/package.json#L25):

I think this is the only dependency it uses old version of `graceful-fs`.

**Comment by imlucas** [comment]
Waiting for Windows CI build to finish in #104.  Will publish new release when build finishes.

**Comment by cognitom** [comment]
Hi @imlucas, `mongodb-version-manager` is still pointing older version?
https://github.com/mongodb-js/version-manager/blob/v1.0.6/package.json#L52

**Comment by imlucas** [comment]
@cognitom I just published `mongodb-version-manager@1.0.7` which contains your fix

https://github.com/mongodb-js/version-manager/blob/master/package.json#L52

**Comment by cognitom** [comment]
@imlucas great! Thank you so much 😄

**Comment by cognitom** [comment]
Oops, I've found one more.
@imlucas could you have a look at this, too?
https://github.com/mongodb-js/download-url/blob/v0.1.10/package.json#L28

*Note*: `^0.0.3` doesn't include `0.0.4` in [semver](https://github.com/npm/node-semver#caret-ranges-123-025-004).
