### ISSUE TITLE
command not found: mongodb-runner start

### ISSUE THREAD

**Issue by shon3005** [mongodb-js/runner#89]
So after npm install -g parse-server mongodb-runner, i tried to run mongodb-runner start.

An error popped up that said 'command not found: mongodb-runner start'

**Comment by HeinrichFilter** [comment]
Are you sure you installed it globally i.e. with `-g`? That's the error message you get when installing locally but trying to invoke the global installation.

If installed without `-g`, then it goes into the project's `node_modules` directory. Then you can run mongodb-runner using:
`node_modules/mongodb-runner/bin/mongodb-runner.js start`


Alternatively, you can add a scripts section to your `package.json` to look something like this:
```json
{
  "scripts": {
    "start": "mongodb-runner start",
  }
}
```

Then you can run it using:
`npm start`

**Comment by imlucas** [comment]
Thanks for the excellent answer, @HeinrichFilter!

@shon3005 are you still experiencing this issue? If so, please feel free to reopen.
